// NodeWarden Local — one-command system service registration.
//
// Detects the host init system and installs NodeWarden as a boot-time service:
//   - systemd (Debian / Ubuntu / CentOS / Arch / ...)
//   - OpenRC (Alpine Linux)
//
// Usage (run the single-file binary as root):
//   ./nodewarden-linux-x64 --install-service
//   ./nodewarden-linux-x64 --uninstall-service
//   ./nodewarden-linux-x64 --help
//
// Test override: set NODEWARDEN_SERVICE_PREFIX=/tmp/xxx to write the unit files
// under a fake root instead of / (never runs systemctl/rc-update in that mode).

import { existsSync, readFileSync, writeFileSync, chmodSync, mkdirSync, rmSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import type { LocalConfig } from './env';

export type InitSystem = 'systemd' | 'openrc' | 'unknown';

const SERVICE_NAME = 'nodewarden';

export function detectInitSystem(): InitSystem {
  // Test / manual override: NODEWARDEN_SERVICE_INIT=systemd|openrc
  const override = process.env.NODEWARDEN_SERVICE_INIT;
  if (override === 'systemd' || override === 'openrc') return override;
  // systemd: PID 1 is "systemd" and /run/systemd/system exists.
  try {
    const pid1 = readFileSync('/proc/1/comm', 'utf8').trim();
    if (pid1 === 'systemd' || existsSync('/run/systemd/system')) return 'systemd';
  } catch {
    // ignore
  }
  // Alpine uses OpenRC.
  try {
    if (existsSync('/etc/alpine-release')) return 'openrc';
  } catch {
    // ignore
  }
  return 'unknown';
}

function isRoot(): boolean {
  try {
    return typeof process.getuid === 'function' && process.getuid() === 0;
  } catch {
    return false;
  }
}

/** Secret persisted separately so it is not visible in `systemctl cat`. */
function ensureSecretFile(prefix: string, config: LocalConfig): { path: string; jwtSecret: string } {
  const dir = prefix === '' ? '/etc' : `${prefix}/etc`;
  mkdirSync(dir, { recursive: true });
  const path = `${dir}/nodewarden.env`;
  const jwtSecret = config.jwtSecret || randomBytes(48).toString('hex');
  if (!existsSync(path)) {
    writeFileSync(path, `JWT_SECRET=${jwtSecret}\n`, { mode: 0o600 });
  } else {
    const existing = readFileSync(path, 'utf8').match(/JWT_SECRET=(.+)/)?.[1]?.trim();
    if (existing) {
      return { path, jwtSecret: existing };
    }
    writeFileSync(path, `JWT_SECRET=${jwtSecret}\n`, { mode: 0o600 });
  }
  try {
    chmodSync(path, 0o600);
  } catch {
    // ignore
  }
  return { path, jwtSecret };
}

function systemdUnit(config: LocalConfig, execPath: string, envFile: string): string {
  return `# NodeWarden Local — generated by "nodewarden --install-service".
[Unit]
Description=NodeWarden Local password vault (Bitwarden-compatible)
Documentation=https://github.com/guimoyun/nodewarden-WL
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${execPath}
Restart=always
RestartSec=3
EnvironmentFile=${envFile}
Environment=NODEWARDEN_DATA_DIR=${config.dataDir}
Environment=NODEWARDEN_DIST_DIR=${config.distDir}
Environment=HOST=${config.host}
Environment=PORT=${config.port}
LimitNOFILE=65536
# Hardening
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
`;
}

function openrcScript(config: LocalConfig, execPath: string, envFile: string): string {
  return `#!/sbin/openrc-run
# NodeWarden Local — generated by "nodewarden --install-service".
name="NodeWarden Local password vault"
description="Bitwarden-compatible password vault (standalone)"
command="${execPath}"
command_background=true
pidfile="/run/nodewarden.pid"
command_user="root"
rc_ulimit="-n 65536"

: "\${JWT_SECRET:=}"
if [ -f "${envFile}" ]; then
  . "${envFile}"
fi
export JWT_SECRET
export NODEWARDEN_DATA_DIR="${config.dataDir}"
export NODEWARDEN_DIST_DIR="${config.distDir}"
export HOST="${config.host}"
export PORT="${config.port}"

depend() {
  need net
  after firewall
}
`;
}

export function installService(config: LocalConfig): { ok: boolean; init: InitSystem; message: string; unitPath: string } {
  const prefix = process.env.NODEWARDEN_SERVICE_PREFIX || '';
  const init = detectInitSystem();
  if (prefix === '' && !isRoot()) {
    return { ok: false, init, message: '需要 root 权限：请用 sudo 执行（sudo ./nodewarden-linux-x64 --install-service）', unitPath: '' };
  }
  if (init === 'unknown') {
    return {
      ok: false,
      init,
      message:
        '无法识别系统服务管理器（未检测到 systemd 或 Alpine OpenRC）。' +
        '本程序支持 Debian/Ubuntu（systemd）与 Alpine Linux（OpenRC）。' +
        '其它发行版请手动配置。',
      unitPath: '',
    };
  }

  const execPath = process.execPath;
  const { path: envFile, jwtSecret } = ensureSecretFile(prefix, config);
  void jwtSecret;

  if (init === 'systemd') {
    const unitDir = `${prefix}/etc/systemd/system`;
    mkdirSync(unitDir, { recursive: true });
    const unitPath = `${unitDir}/${SERVICE_NAME}.service`;
    writeFileSync(unitPath, systemdUnit(config, execPath, envFile), { mode: 0o644 });
    if (prefix === '') {
      execFileSync('systemctl', ['daemon-reload']);
      execFileSync('systemctl', ['enable', SERVICE_NAME]);
      execFileSync('systemctl', ['restart', SERVICE_NAME]);
    }
    return {
      ok: true,
      init,
      message: `已安装 systemd 服务 ${SERVICE_NAME} 并启动。管理命令：systemctl status ${SERVICE_NAME} / journalctl -u ${SERVICE_NAME} -f`,
      unitPath,
    };
  }

  // OpenRC (Alpine)
  const initDir = `${prefix}/etc/init.d`;
  mkdirSync(initDir, { recursive: true });
  const unitPath = `${initDir}/${SERVICE_NAME}`;
  writeFileSync(unitPath, openrcScript(config, execPath, envFile), { mode: 0o755 });
  chmodSync(unitPath, 0o755);
  if (prefix === '') {
    execFileSync('rc-update', ['add', SERVICE_NAME, 'default']);
    execFileSync('rc-service', [SERVICE_NAME, 'start']);
  }
  return {
    ok: true,
    init,
    message: `已安装 OpenRC 服务 ${SERVICE_NAME} 并启动（开机自启）。管理命令：rc-service ${SERVICE_NAME} status`,
    unitPath,
  };
}

export function uninstallService(config: LocalConfig): { ok: boolean; init: InitSystem; message: string } {
  void config;
  const prefix = process.env.NODEWARDEN_SERVICE_PREFIX || '';
  const init = detectInitSystem();
  if (prefix === '' && !isRoot()) {
    return { ok: false, init, message: '需要 root 权限：请用 sudo 执行（sudo ./nodewarden-linux-x64 --uninstall-service）' };
  }
  try {
    if (init === 'systemd') {
      if (prefix === '') {
        execFileSync('systemctl', ['stop', SERVICE_NAME]);
        execFileSync('systemctl', ['disable', SERVICE_NAME]);
      }
      rmSync(`${prefix}/etc/systemd/system/${SERVICE_NAME}.service`, { force: true });
      if (prefix === '') execFileSync('systemctl', ['daemon-reload']);
      return { ok: true, init, message: `已卸载 systemd 服务 ${SERVICE_NAME}` };
    }
    if (init === 'openrc') {
      if (prefix === '') {
        execFileSync('rc-service', [SERVICE_NAME, 'stop']);
        execFileSync('rc-update', ['del', SERVICE_NAME]);
      }
      rmSync(`${prefix}/etc/init.d/${SERVICE_NAME}`, { force: true });
      return { ok: true, init, message: `已卸载 OpenRC 服务 ${SERVICE_NAME}` };
    }
    return { ok: false, init, message: '未检测到 systemd 或 OpenRC，无需卸载' };
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    return { ok: false, init, message: `卸载失败：${msg}` };
  }
}

export function printHelp(): void {
  console.log(`NodeWarden Local — Bitwarden-compatible password vault (standalone)
Bitwarden 兼容密码库（独立可执行版）

Usage / 用法:
  ./nodewarden-<platform>                      Start Web Vault (default 0.0.0.0:8787) / 启动密码库
  ./nodewarden-<platform> --install-service   Register as a system service (systemd / OpenRC) / 一键注册系统服务
  ./nodewarden-<platform> --uninstall-service Remove the service / 卸载系统服务
  ./nodewarden-<platform> --help              Show this help / 显示本帮助

Environment variables / 环境变量:
  JWT_SECRET              Required signing secret (>=32 chars) / 必填签名密钥；
                          --install-service generates and saves it to /etc/nodewarden.env automatically
  NODEWARDEN_DATA_DIR     Data dir (vault SQLite), default ./nw-data / 数据目录，默认 ./nw-data
  NODEWARDEN_DIST_DIR     Web Vault assets dir, default ./dist / 前端资源目录，默认 ./dist
  HOST / PORT             Listen address / port, default 0.0.0.0 / 8787
  NODEWARDEN_UPDATE_TOKEN GitHub token for one-click update (optional) / 一键更新 GitHub Token（可选）
  NODEWARDEN_UPDATE_MIRROR Download mirror prefix (optional) / 一键更新下载镜像前缀（可选）
`);
}
